platform :ios, '9.0'
use_frameworks!

target 'LFTwitterProfile_Example' do
  pod 'LFTwitterProfile', :path => '../'

  target 'LFTwitterProfile_Tests' do
    inherit! :search_paths


  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
